### ISSUE TITLE
Decoupled Preview Links

### ISSUE THREAD

**Issue by Snugug** [Lullabot/ibm-dte#9]
## Problem
Given a decoupled website, we want to be able to be able to provide our content creators with the ability to see a representation of their content, at any stage in the content moderation process from initial draft to final published version, live on the decoupled front-end. With this, we should be able to distinguish between a staging website for content that isn't published and a production website where content is published.

---
Some initial implementation thoughts:
* Configuration of staging/production preview URLs with token replacement
* Preview link available for content in moderation based off of staging URL
* View link available for published content based on production URL
* Revisions form updated to include respective links
* iFrame available to embed live preview directly in content display, possibly powered by [ish](https://github.com/bradfrost/ish.)

**Comment by sethlbrown** [comment]
Additional context from Sam on Aug. 20:


_Provide a link from any revision to a 3rd party URL, with some form of token support to dynamically generate the URLs_
The goal of this work would be to enable staging and production previews/links for content creators for decoupled displays.
• Ideally, we’d be able to configure a URL for both content in moderation (and revisions) as well as published revisions separately (thus allowing for staging and production links). We’d also want to have tokens of some sort to allow the URLs to dynamically change, so I could say something like `https://staging.foo.com/[entity:fieldable_path]` and that could render as `https://staging.foo.com/article/bar-baz`.
• These links could have configurable text to describe them/be the test in the link
• There would be a link available on the actual node view page, as well as links per revision on the revision table
• Bonus points if we could get a block or a tab or something that includes the ability to choose the revision to display inside of an ish (https://github.com/bradfrost/ish.) or equivalent iframe for an embedded responsive preview

**Comment by sethlbrown** [comment]
Mateu—The problem: We have privileged users that want to see how the website will look in the future. This privileged users should make a call to the API to load the revision we're working on. Right now we've been testing calls in browser and it works because browser is sending authentication cookie for the Drupal side. If we want to do this in decoupled way, need to have a token for auth.

Sam—Token not for authentication but to dynamically build a link dynamically, I want a token for node path to map to a preview of a revision. Preview link URL building. 

Mateu—user workflow of this, who is doing this, where, on what platform? is this on editorial Drupal backend where they get these links? is it same editor who put content or draft up?

Workflow
----------
- Editors want to go into Drupal, start creating content, save a draft, click a link to get a live preview or real-life preview. Our content creators are visual people. Have a hard time separating content display from the content they're creating. Content need to see a live preview. When they create a draft they're given a link to the content. As they flesh out content, they can share links to their preview content at those various stages. A shareable link allows them to solicit feedback. Want to see stuff in a way that's as close to final presentation. Goal is to see it in as many of the live displays as they can. These are all staging websites, not production. Three places where content might appear, technical documentation, marketing site, asset catalog. Give them links to each?
- Example of this: Sally's work on Lullabot.com, live updates staging version of Lullabot.com. Don't need web socket live updates. When a draft is saved want to have a link.

Mateu need one to one correspondence between a website and a node. Previewing in this way forces our hand to have a page that stems from a node. Can't be a random collection of pieces put together via the API. (Sam agrees)

Mateu: see two parts: managing the different consumers we need to preview on. Also managing the different versions we want to preview. I'm guessing we want to preview just latest version and working copy? Arbitrary revision ids? (Sam: arbitrary revision ids would be nice to have.)

On the workflow page, add a column, preview this in the website.

Or on the view tab of latest piece of content

Having links on latest review pages. ( Mateu: Delta between them is not big. )

We're describing similar solution to what's on Lullabot.com. UX would be slightly different on D8.

Can use consumers module. That would allow us to add fields, those fields could be tokenized url. Going to rely on a custom module. Could be a contrib module?

Sam: I want as much as possible for our work to be open source even if its minimally maintained. Let's me distribute. I got into Drupal to do open source in the first place. Github or D.o would be fine. Solution should be extensible for usual contrib work. Allow for others to adapt your work. We'll do this inside Github we have now. We can put it out later.

[Mateu speculates:] We're not using this Github for our codebase. Want it to be compatible with Composer. Maybe a new repo is the easiest way?

Sam: Could be called Decoupled Preview Links. Sam doesn't remember how to create a module, could use help on that, but can probably figure it out.

Mateu: We either allow anyone to preview content or we make all consumers deal with authentication. When you create this link what you're telling the application, I just gave you a link of what to load, if not authenticated won't be able to load from JSON API, open this to everyone? Auth would be handled by VPN, staging environments aren't public facing.

Sam: break into revisions and production, n number of links for both revisions and production, production.example.com/[token-path]/asset-catalog/my_great_content

[Sam explains tokens:] Think of tokens like path auto except your specifying path auto setting and base url and you use that to generate a full link instead of just a slug.

Mateu: Token path filled in by editor, managed by fieldable path, or something auto-computed on node properties like path auto does.

Sam: fieldable path might be tutorial/my-awesome-tutorial on our website might be [product-name]/tutorial/my-awesome-tutorial where product name include example.com/[node:related-production]/[machine-name]/[node:_fieldable-path]/tutorial/my-awesome-tutorial

Leave it to implementer to decide full token path

M: When you say authentication is dealt with server-side, do we need to worry about that? 
S: Don't need to worry about that but I want to run my solution by you. Thinking off implementing http basic auth provider for our apis and making a role that's just api consumer for staging and production, manually generate strong usrenames and passwords and only giving those access, need to make these api requests without some user doing oauth, not actually having users log into our system. This is all authenticated traffic more or less. 
M: Just have a different configuration for Drupal in the staging and prod environment, in staging, need access that's not publically available, preview public based on being inside a VPN
S: Need auth method, one set of apis, they're in production, whether you get staging or prod, depends on whether you're viewing a revision or not a revision b/c we don't have. Still need to lock down actual API access so randoms don't come in and view our content. HTTP Auth from server side would further protect with different users for staging and prod. Staging site would be a single user to access APIs. Production site would be a single user to access APIs.

M: Will need a new module, decoupled_preview_links and auth seems like we shouldn't worry about. Just make sure it's extensible. Good MVP will be to just have the links. If you need hand-holding for auth, we can provide that.

**Comment by sethlbrown** [comment]
Simple experience: just a link that links to revision on staging site
More advanced experience: tabbed experience with Drupal content preview in one tab and an i-framed inlay of the staging site in another, where could control what revision was visible. Add Brad Frost's [ish](http://bradfrost.com/demo/ish/) tool that provides a responsive preview window.

Could just do simple if we're short on time.

**Comment by sethlbrown** [comment]
To dos
------------
- [ ] Daniel to make desired viewport sizes for ish configurable in consumers module
- [ ] Would like preview of specific revision ids if possible
- [ ] Add tabs for preview staging and preview live, will include an additional url field in consumers module configuration screen
- [ ] Make url for 'ish' clickable in 'ish' preview, link out to a new tab
- [ ] Tab nomenclature: 'View Live Version' 'Preview Latest Draft'

**Comment by sethlbrown** [comment]
Notes from Friday, September 28, 2018
---------------
Use ish sizes

S: 240-500
M: 500-800
L: 800-1200
XL: 1200-Full Width
Full
Random

* Sam wants consumers to be config not content

**Comment by dawehner** [comment]
After some discussion with Snugug today there is a new release of the DPL module

* Addresses all the point from the last meeting notes
* Uses some nice CSS from @Snugug himself
* Uses config entities now for storage. All actual logic uses a value object, so changing this in the future would be less of a deal.

**Comment by sethlbrown** [comment]
Confirmed completion

**Comment by ElijahLynn** [comment]
For anyone coming across this seeing "DPL Module" it is the Decoupled Preview Link module and here are the releases. https://www.drupal.org/project/dpl/releases
